Set target properties *_POSTFIX instead of global vars CMAKE_*_POSTFIX
libexpat/libexpat pull request #608
Opened 2022-06-29 14:39 UTC by dfaure-kdab

This fixes unwanted side effects when libexpat is used with FetchContent
in another cmake-based project. Setting CMAKE_*_POSTFIX affects the
whole project, while here we only want to define the postfix for libexpat
itself.

2022-07-14 21:24 UTC, hartwork requested changes
Hi @dfaure-kdab ,

I understand and support the general direction, thanks for bringing this up :+1: 
On a few details:

- Is there a strong reason why the code has been moved down in the file?
  Else, let's move it back in place fore a more self-explaining diff, please.

- Previously, defining `CMAKE_*_POSTFIX` variables would affect Expat:
  ```
  # git clone --depth 1 https://github.com/libexpat/libexpat/
  # cd libexpat/expat
  # cmake -S . -DCMAKE_NOCONFIG_POSTFIX=abc | fgrep abc
  --   Library name postfix ....... abc
  ```
  After this pull request it no longer will.  Maybe we should to do additional `if(DEFINED ..)` work to keep that behavior intact?

- There is a section in the readme about available options and the command to generate the related listing at the very bottom of the file. It would be nice to get the listing in the readme back in sync now that we add four more public variables.

2022-07-15 22:55 UTC, hartwork requested changes
PS: @dfaure-kdab a quick update:

Regarding my comment above about keeping support for explicit `CMAKE_${postfix_var}`, I believe we would need this order of preference:

  1. Explicit `EXPAT_${postfix_var}`
  2. Explicit `CMAKE_${postfix_var}`
  3. Computed default value
    
When drafting an implemenation over here, I envisioned something like this:

```cmake
if(NOT DEFINED EXPAT_${postfix_var})
    if(DEFINED CMAKE_${postfix_var})
        set(EXPAT_${postfix_var} "${CMAKE_${postfix_var}}" CACHE ......)
    else()
        set(EXPAT_${postfix_var} "${_POSTFIX_WIDE}${_POSTFIX_DEBUG}${_POSTFIX_CRT}" CACHE ......)
    endif()
endif()

set_property(TARGET expat PROPERTY ${postfix_var} "${EXPAT_${postfix_var}}")
```

PS: With the Cppcheck warning fixed by merged pull request #610, a rebase onto latest `master` has realistic chances on a green CI.

Looking forward to what you think, cheers :beers:

2022-07-17 15:16 UTC, hartwork requested changes
@dfaure-kdab maybe I'm over-complicating. Maybe plain `EXPAT_${postfix_var}` is enough: It can do everything and the build system does not have strict requirements on a stable API…

2022-07-27 17:02 UTC, dfaure-kdab commented
>     * Is there a strong reason why the code has been moved down in the file?

Yes, I like diffs to be as difficult to read as possible :-)
More seriously, this is because `set_property(TARGET expat ...` requires the target `expat` to have been defined first.

>     * Previously, defining `CMAKE_*_POSTFIX` variables would affect Expat:
>       ```
>       # git clone --depth 1 https://github.com/libexpat/libexpat/
>       # cd libexpat/expat
>       # cmake -S . -DCMAKE_NOCONFIG_POSTFIX=abc | fgrep abc
>       --   Library name postfix ....... abc
>       ```
>       After this pull request it no longer will.  Maybe we should to do additional `if(DEFINED ..)` work to keep that behavior intact?

Are you aware of anyone actually doing that? I wonder if there's a real-world use case.

>     * There is a section in the readme about available options and the command to generate the related listing at the very bottom of the file. It would be nice to get the listing in the readme back in sync now that we add five more public variables.

Fair point (although it's discoverable in cmake-gui).

> Maybe plain EXPAT_${postfix_var} is enough

I would think so too, if indeed the use cases for changing the default postfixes are very rare corner cases.
Generally speaking I see the point of preserving source compatibility - in the buildsystem too - but whether the complexity of the resulting cmakelists code is worth it.... that's for you to decide, really :-)

2022-07-27 21:17 UTC, hartwork commented
> Yes, I like diffs to be as difficult to read as possible :-) More seriously, this is because `set_property(TARGET expat ...` requires the target `expat` to have been defined first.

@dfaure-kdab thanks for the explanation :+1: 

> Are you aware of anyone actually doing that? I wonder if there's a real-world use case.

Not aware of any at the moment, no. 

> Fair point (although it's discoverable in cmake-gui).

In the interest of moving forward, I'll do readme fixing in a _new_ pull request myself and merge what we have here now. I hope that's in your interest, too.

2022-07-27 21:17 UTC, merged