Update legal name of Donghee Na
libexpat/libexpat pull request #754
Opened 2023-09-22 16:13 UTC by corona10

Hi, my English legal name was updated from "Dong-hee Na" to "Donghee Na"
There was several issues with my legal English name, so I would like to request updating my legal name in this repo too :)

Related story: https://x.com/dongheena92/status/1702490849282810223?s=20

2023-09-22 16:23 UTC, hartwork reviewed
Hi @corona10,

I believe there may be two more places where this change should be applied:

#### 1. The change log

```console
# git --no-pager grep -n Dong-hee
expat/Changes:329:            Dong-hee Na
```

#### 2. Git `.mailmap` file

…at https://github.com/libexpat/libexpat/blob/master/.mailmap

```console
# git log | grep "Author: Dong-hee"
Author: Dong-hee Na <donghee.na@python.org>
```

What do you think?

2023-09-23 00:09 UTC, corona10 commented
@hartwork Thank you for catching this :)

2023-09-24 12:06 UTC, hartwork requested changes
@corona10 we're almost there, please see the two comments below:

2023-09-24 12:06 UTC, hartwork commented on .mailmap
> +Donghee Na <donghee.na@python.org>
While the entry looks good and seems to work well in practice, previously the lines in this file were sorted alphabetically. Could you move this line after `Ben Wagner` please?

2023-09-24 12:06 UTC, hartwork commented on expat/Changes
> +
Please revert the unrelated changes in white space to this file, thanks!

2023-09-24 13:10 UTC, corona10 commented
@hartwork Done thanks!

2023-09-24 13:11 UTC, hartwork commented on expat/Changes
> +          #1983953, 2517952, 2517962, 2649838:
@corona10 there is one more unrelated whitespace change here^^

2023-09-24 13:13 UTC, hartwork approved these changes
@corona10 thanks for the adjustments!

2023-09-24 13:13 UTC, merged