fuzz: improve coverage by maybe stopping parser
libexpat/libexpat pull request #801
Opened 2024-01-15 10:09 UTC by catenacyber

@hartwork what do you think about this to make `internalEntityProcessor` reachable by fuzzing ?

If it looks good, I will put it in xml_parsebuffer_fuzzer.c as well

2024-01-15 16:17 UTC, hartwork requested changes
Hi @catenacyber thanks for the PR, here's what I found:

2024-01-15 20:24 UTC, catenacyber commented on expat/fuzz/xml_parse_fuzzer.c
> +XML_Parser g_parser;
nicer indeed

2024-01-15 20:26 UTC, catenacyber commented on expat/fuzz/xml_parse_fuzzer.c
> +    XML_SetCharacterDataHandler(g_parser, NULL);
I just copied this from `clearing_aborting_character_handler` 
It was this handler which I found by running the unit tests with a panic on the `internalEntityProcessor`

2024-01-15 20:28 UTC, catenacyber commented on expat/fuzz/xml_parse_fuzzer.c
> +may_stop_handler(void *userData, const XML_Char *s, int len) {
ok for me

2024-01-15 21:03 UTC, hartwork commented
PS: @catenacyber cppcheck failure https://github.com/libexpat/libexpat/actions/runs/7533731319/job/20507404878?pr=801 is not your fault. I will take over for a dedicated pull request addressing that issue.

2024-01-15 22:50 UTC, hartwork commented
PS: @catenacyber waiting for CI at #803…

2024-01-15 23:03 UTC, hartwork requested changes
@catenacyber my current plan is this:
- [ ] I get the CI green for both…
    - [ ] #799 and
    - [ ] #803

     …, a mix-up re-try and waiting, work in progress, finished by some time tomorrow worst case
- [ ] Merge these two
- [ ] You duplicate the changes to the sibling fuzzer
- [ ] And rebase onto latest master
- [ ] We we then get the CI green for #801 here
- [ ] And merge

What do you think?

2024-01-16 10:09 UTC, catenacyber commented
> * [x]  You duplicate the changes to the sibling fuzzer
> * [x]  And rebase onto latest `master`
> 
> What do you think?

Just did this

2024-01-16 15:43 UTC, catenacyber commented
CI says

> libexpat/expat/fuzz/xml_parsebuffer_fuzzer.c:74: void ParseOneInput(XML_Parser, const uint8_t *, size_t): Assertion `buf' failed.

Should the assert be turned into a `return` ?

2024-01-16 17:17 UTC, hartwork commented
> CI says
> 
> > libexpat/expat/fuzz/xml_parsebuffer_fuzzer.c:74: void ParseOneInput(XML_Parser, const uint8_t *, size_t): Assertion `buf' failed.
> 
> This is the return value of `XML_GetBuffer`
> 
> Should the assert be turned into a `return` ?

@catenacyber that would work, yes. An alternative to maybe try would be to reduce the number of jobs in the CI so that it does not run out of memory. `nproc` seems to be 4 in practice, we could try with `-jobs=2` instead before accepting out-of-memory. What do you think?

2024-01-16 21:13 UTC, catenacyber commented
Turning assert on allocation failures into returns...

This way, we also get the benefit of nallocfuzz to work ;-)

2024-01-16 21:41 UTC, hartwork requested changes
@catenacyber I'm not a fan of the new version, because OOM from `XML_GetBuffer` means that that fuzzing case becomes useless (meaning it can no longer find issues for that case) while it could be of use and functional with lower parallelism. Please revert this change and try `-jobs=2` before we go unto `goto` complexity that hides away a problem rather than solving it. Thank you.

2024-01-16 21:57 UTC, hartwork commented
PS: @catenacyber 2 jobs is still crashing, now trying a single job…

2024-01-16 22:17 UTC, hartwork commented
Update: @catenacyber even `-jobs=1` is failing, trying the least invasive robustness fix (commit b1f5aa5a85bbc5610e7311bf5da10ab031e933f3) with original `-jobs=$(nproc)` now at https://github.com/libexpat/libexpat/actions/runs/7548178383 …

2024-01-16 22:31 UTC, hartwork commented
@catenacyber please replace the second commit by a cherry-pick to ceaeeee7602da1157a9b499f39422433dde21b2e and if the CI is still green, we're ready to merge. Good?

2024-01-17 09:09 UTC, catenacyber commented
> please replace the second commit by a cherry-pick to [ceaeeee](https://github.com/libexpat/libexpat/commit/ceaeeee7602da1157a9b499f39422433dde21b2e) and if the CI is still green, we're ready to merge. Good?

Done. Nice commit hash ;-)

2024-01-17 16:36 UTC, merged