configure.ac: only treat #define.*SIZEOF_VOID_P as error
libexpat/libexpat pull request #845
Opened 2024-03-11 14:21 UTC by xypiie

Don't throw error in case autoreconf/autoheader puts
 #undef SIZEOF_VOID_P
into expat_config.h.in.

2024-03-11 18:35 UTC, hartwork approved these changes
@xypiie that seems like a good idea! Could you share what what environment you ran into cases like that, which version of things, which operating system? Thanks!

2024-03-11 18:44 UTC, hartwork requested changes
@xypiie luckily I remembered last minute that autoheader adds the entty as `#undef SIZEOF_VOID_P`, so that this pull requests re-creates the issue rather than fixing it:

```console
$ autoheader && grep SIZEOF_VOID_P expat_config.h.in
#undef SIZEOF_VOID_P
```

So I'll have to close this as mistaken. Please let me know which part of the error message was not clear so that you felt like patching things rather than doing what it suggested. Thanks!

2024-03-11 18:45 UTC, closed without merging

2024-03-12 19:10 UTC, hartwork commented
@xypiie the short version is that configure needs `SIZEOF_VOID_P` to mimic CMake's `CMAKE_SIZEOF_VOID_P` when rendering template `cmake/autotools/expat-config-version.cmake.in` but autoheader considers the variable it relevant to `expat_config.h.in` and adds it there. As a result, distros with multilib support — 32bit and 64bit support — would then get `SIZEOF_VOID_P` with one shared value while they would need say 8 for 64bit and 4 for 32bit. Hence the value cannot be in the installed rendered `expat_config.h` header or it would break multilib. Pull request #490 has the start of that story. PS: `configure` would turn `#undef SIZEOF_VOID_P` into `#define SIZEOF_VOID_P 8` or so at runtime, so the line cannot even be in that file. Other workarounds may be possible, but that's what we have right now.

2024-03-13 07:53 UTC, xypiie commented
@hartwork : thank you very much for this description, this clarifies it for me.
If you find some time, it would be great if you could put this description as comment into the according part of configure.ac/buildconf.sh
Just in case someone else stumbles over this and gets confused.

2024-03-13 13:44 UTC, hartwork commented
@xypiie I'll consider something like it, but I'll need to get 2.6.2 out the door first, today. Let's see after.