Don't require dos2unix.
libexpat/libexpat pull request #863
Opened 2024-04-22 15:27 UTC by dag-erling

2024-04-23 01:24 UTC, emaste commented
This looks good to me

2024-04-23 15:07 UTC, hartwork requested changes
Hi @dag-erling,

some bits are nice, some details are not great yet and likely need adjustment, let's find out.

On the big picture front, this lacks an "official motivation", i.e. a reason why installing dos2unix would be a problem or an improvement or relevance. From https://man.freebsd.org/cgi/man.cgi?query=dos2unix& it seems that FreeBSD has `dos2unix` so I would like to understand and have documented who we are avoiding dos2unix for.

On the detail level, it would be nice to have commented that `tr -d '\r'` is meant to be portable dos2unix, in code.

An then the …

```
tr -d '\r' <"${filename}" |
sed \
```

…is surprising to work because of lack of a trailing `\` in the `tr` line, and to continue without indentation on the next line is also too easy to misread as two consecutive commands rather than a chain or "shell job".  So there would ideally be one last separate commit fixing  the (or adding new) indentation to all parts of the `sed` call, after adding the trailing backslash and adding a comment on why and who for we do that `tr` call.

I hope that's an okay level of picky, I have re-evaluated it for myself and stand behind that being the feedback I want to share.

Thanks in advance for the adjustments :pray:

2024-04-23 15:16 UTC, dag-erling commented
FreeBSD does not ship with dos2unix preinstalled. Neither do macOS, or Debian, or RHEL, or any other mainstream OS I'm aware of. It is usually available as a package, but why add this needless (and undocumented) dependency when a standard POSIX tool can to the job just as easily?

2024-04-23 15:26 UTC, hartwork commented
> > seems that FreeBSD has `dos2unix`
> 
> We do have dos2unix in FreeBSD ports, but it is not installed by default (and isn't on my daily driver dev laptop). I think `tr` is going to be available pretty much universally (in e.g. coreutils or so in the Linux ecosystem).

> FreeBSD does not ship with dos2unix preinstalled. Neither do macOS, or Debian, or RHEL, or any other mainstream OS I'm aware of. It is usually available as a package, but why add this needless (and undocumented) dependency when a standard POSIX tool can to the job just as easily?

@emaste @dag-erling thanks for your insights. `tr` is GNU Coreutils, I confirm. One reason to use command `dos2unix` has been that it is highlevel in the sense that its motive of use explains itself while `tr -d '\r'` is low-level, needs longer to grasp, does not explain it's high level mission: it needs commenting with regard to intention, not with the actual command. We can do that change but it only affects building Expat rather than running Expat and installing dos2unix in packaging should not be a problem in most scenarios, unless we're in cyclic dependency zone. So let's do that change for FreeBSD but add the missing high level explanation in code then.

PS: To be clear, I will not accept patches getting Bashisms out of Shell scripts: Bash will remain a hard build requirement and is available everywhere; if you have plans in that direction, just to avoid potential disappointment and waste of time upfront.

2024-04-23 17:20 UTC, emaste commented
> Bash will remain a hard build requirement and is available everywhere

Thanks for explicitly setting expectations :)  Bash is pretty much unavoidable, and as long as it doesn't have to be installed as `/bin/bash` it's no issue.

2024-04-23 18:11 UTC, hartwork commented
@emaste I confirm that `/usr/bin/env bash` is both status quo and future target for new script files, yes, not `/bin/bash`.

2024-05-02 21:35 UTC, dag-erling commented
I renamed the branch thinking GitHub would DTRT but it just closed the PR instead...

2024-05-02 22:01 UTC, hartwork requested changes

2024-05-02 22:34 UTC, dag-erling commented on expat/fix-xmltest-log.sh
> +# tr strips CR from CR LF pairs
What if I fold it into the sed command? We could even drop the temp file. While sed does not allow `\r` in patterns, we can get the shell to pass it in: `$'s/\r//'`. It's not a very common idiom but it's in POSIX.

2024-05-02 22:38 UTC, dag-erling commented on expat/fix-xmltest-log.sh
> +# tr strips CR from CR LF pairs
If the proof of concept looks ok I'll squash and force-push.

2024-05-02 22:57 UTC, hartwork requested changes
@dag-erling a rebase against latest master with #868 merged for green CI and resolved conflicts would be great, thanks!

2024-05-02 22:57 UTC, hartwork commented on expat/fix-xmltest-log.sh
> +        -e '# convert DOS line endings without resorting to dos2unix' \
Please mention the target of the conversion please — Unix line endings — not just the source, since conversion has two sides. Thanks!

2024-05-02 23:02 UTC, hartwork commented on expat/fix-xmltest-log.sh
> +        -e '# convert DOS line endings without resorting to dos2unix' \
@dag-erling PS: yes, we have it in "dos2unix". To "convert DOS line endings" still feels off without saying where to. It's not a requirement to merge, but would be nice and symmetric, and not delay understanding to the end of the sentence.

2024-05-04 14:06 UTC, hartwork approved these changes

2024-05-04 14:06 UTC, merged